name: deepmod2
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - numpy
  - pysam
  - python>=3.8
  - pytorch
  - h5py
  - tqdm
  - numba
  - ont-fast5-api
  - pip
  - pip:
    - pod5
